### ISSUE TITLE
Can't connect, error

### ISSUE THREAD

**Issue by Barabba11** [ubidots/ubidots-nodered#31]
Hi, I've just installed your node, I?ve generated token pan past into node, the firsr time I deploy (full) it writes connected for a fraction of second, then disconnected and retries. What is wrong here?

**Comment by Barabba11** [comment]
```
Publisher: Inside error function, msg:  Error: Connection refused: Bad username or password
    at MqttClient._handleConnack (C:\Users\Admin\.node-red\node_modules\ubidots-nodered\node_modules\mqtt\lib\client.js:735:9)
    at MqttClient._handlePacket (C:\Users\Admin\.node-red\node_modules\ubidots-nodered\node_modules\mqtt\lib\client.js:296:12)
    at process (C:\Users\Admin\.node-red\node_modules\ubidots-nodered\node_modules\mqtt\lib\client.js:238:12)
    at Writable.writable._write (C:\Users\Admin\.node-red\node_modules\ubidots-nodered\node_modules\mqtt\lib\client.js:248:5)
    at doWrite (C:\Users\Admin\.node-red\node_modules\ubidots-nodered\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\Users\Admin\.node-red\node_modules\ubidots-nodered\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at Writable.write (C:\Users\Admin\.node-red\node_modules\ubidots-nodered\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at TLSSocket.ondata (internal/streams/readable.js:719:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by Barabba11** [comment]
bad username or password?? I copied past the token!!

**Comment by Barabba11** [comment]
I was necessary to activate account, but ubidots didn't require it, that's bad. Only when I asked support they asked to activate, and I did
